builds:
  - binary: pwt
    main: cmd/punycoder/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: punycoder
    homepage: "https://github.com/simonmittag/punycoder"
    tap:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com

checksum:
  name_template: 'checksums.txt'